### ISSUE TITLE
Delete or Edit highlight from quick action menu

### ISSUE THREAD

**Issue by GautamChibde** [codetoart/FolioReader-Android#59]

**Comment by zuberkazi** [comment]
**Issue 1-** Delete highlights does not works properly, It fails to delete highlight completely, Also fail to delete from highlight section, Please see below two screenshots.
Screenshot 1- Before delete
Screenshot 2- After delete.

![screenshot_20170913-162451](https://user-images.githubusercontent.com/30237279/30374103-5bbe0766-98a1-11e7-8ab6-09cc1c03ab81.png)
![screenshot_20170913-162508](https://user-images.githubusercontent.com/30237279/30374132-7a8accc4-98a1-11e7-9fd6-ab7c081818e7.png)

**Issue 2-** Changed highlight color does not applies to highlight section. It remains previous color.
